In [1]:
# importing packages

import datapurifier as dp
from datapurifier import Mleda
from datapurifier import Nlpeda
from datapurifier import Nlpurifier, Mlpurifier
from datapurifier import MlReport

from termcolor import colored
import seaborn as sns
import pandas as pd
import numpy as np

print("Data Purifier Version: ", dp.__version__)

Data Purifier Version:  0.2.9

In [2]:
# df = pd.read_csv("./datasets/iris.csv")
# df = pd.read_csv("./datasets/horse_colic.csv")
df = pd.read_csv("./datasets/oil-spill.csv", header=None)
df.head()

,0,1,2,3,4,5,6,7,8,9,...,40,41,42,43,44,45,46,47,48,49
0,1,2558,1506.09,456.63,90,6395000.0,40.88,7.89,29780.0,0.19,...,2850.00,1000.00,763.16,135.46,3.73,0,33243.19,65.74,7.95,1
1,2,22325,79.11,841.03,180,55812500.0,51.11,1.21,61900.0,0.02,...,5750.00,11500.00,9593.48,1648.80,0.60,0,51572.04,65.73,6.26,0
2,3,115,1449.85,608.43,88,287500.0,40.42,7.34,3340.0,0.18,...,1400.00,250.00,150.00,45.13,9.33,1,31692.84,65.81,7.84,1
3,4,1201,1562.53,295.65,66,3002500.0,42.40,7.97,18030.0,0.19,...,6041.52,761.58,453.21,144.97,13.33,1,37696.21,65.67,8.07,1
4,5,312,950.27,440.86,37,780000.0,41.43,7.03,3350.0,0.17,...,1320.04,710.63,512.54,109.16,2.58,0,29038.17,65.66,7.35,0

In [4]:
# report = MlReport(df, target_column="species") # iris dataset
# report = MlReport(df, target_column="Outcome") # pima-indians-diabetes dataset
# report = MlReport(df, target_column="outcome") # horse_colic dataset
report = MlReport(df) # oil-spill dataset

Sample of Dataframe:

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48,49
266,208,53,1893.08,1601.11,52,132500.0,33.57,4.18,1400.0,0.12,94.6,0.18,0.20,0.29,0.09,0.20,62.12,34.55,0.60,0.16,0.19,67.87,0,0.49,421.21,1.83,14.78,-0.06,2.00,-2.44,-0.70,2.16,0.0,2.16,12,720,0.01,14.79,64,39,430.12,250.00,198.06,54.64,2.17,0,9120.29,66.32,8.01,0
447,15,210,1111.80,1889.67,137,295312.0,31.80,8.43,3339.5,0.27,88.4,0.29,0.44,0.94,0.20,0.74,24.34,11.03,0.20,0.25,0.36,126.08,0,0.25,2025.42,-0.53,3.01,1.00,4.95,-6.22,-0.59,2.91,0.0,2.91,46,2340,0.01,37.76,133,85,0.00,0.00,0.00,0.00,0.00,0,14192.31,36.80,14.89,0
196,2,319,798.03,952.23,32,797500.0,29.16,5.88,7780.0,0.20,102.5,0.27,0.31,0.53,0.15,0.38,47.49,15.52,0.52,0.22,0.29,67.87,0,0.43,421.21,1.83,14.78,0.69,3.95,-3.95,-0.33,2.17,0.0,2.17,65,3240,0.00,75.90,64,39,3010.40,430.12,196.51,95.20,15.32,1,12193.37,65.88,7.01,0
917,185,10,59.50,477.30,53,81000.0,54.20,6.61,831.0,0.12,97.5,0.23,0.26,0.33,0.20,0.13,25.95,16.49,0.36,0.22,0.26,55.85,0,0.97,221.97,0.87,5.07,-0.17,2.91,-1.62,-0.36,1.09,0.0,1.09,7,450,0.01,8.53,82,50,381.84,0.00,0.00,0.00,0.00,1,3156.78,65.99,6.17,0
111,101,110,1586.95,942.99,1,275000.0,34.49,8.56,3400.0,0.25,80.9,0.24,0.30,0.50,0.17,0.33,55.45,14.29,1.99,0.21,0.29,75.26,0,0.46,351.67,0.18,9.24,0.93,4.54,-2.82,-0.62,2.17,0.0,2.17,47,2610,0.01,42.04,78,55,1150.00,350.00,191.30,93.73,6.01,0,7555.21,66.01,7.97,0
886,154,10,182.50,460.00,90,81000.0,57.60,8.68,810.0,0.15,100.0,0.28,0.35,0.36,0.30,0.06,17.05,8.46,0.38,0.28,0.35,55.85,0,1.03,221.97,0.87,5.07,-0.58,2.43,-1.67,-0.44,1.09,0.0,1.09,4,360,0.00,8.10,82,50,360.00,90.00,90.00,0.00,4.00,0,6004.08,66.01,6.58,0
132,122,414,1784.95,1752.95,61,1035000.0,31.69,8.79,4860.0,0.28,213.0,0.21,0.32,0.62,0.14,0.48,85.22,31.77,1.83,0.17,0.23,75.26,0,0.42,351.67,0.18,9.24,0.80,6.73,-3.12,-0.29,2.16,0.0,2.16,53,3240,0.00,22.82,78,55,1141.27,1097.72,800.95,196.94,1.42,0,7420.55,66.44,7.92,0
448,16,312,1131.87,1693.07,47,438750.0,30.22,10.80,4857.5,0.36,90.3,0.38,0.46,0.81,0.20,0.61,16.92,7.64,0.19,0.32,0.42,126.08,0,0.24,2025.42,-0.53,3.01,1.57,7.14,-5.84,-0.29,2.91,0.0,2.91,73,3780,0.01,53.78,133,85,0.00,0.00,0.00,0.00,0.00,0,9232.76,36.80,14.97,0
690,43,14,445.21,654.64,21,113400.0,82.64,21.51,868.0,0.26,130.6,0.24,0.23,0.25,0.19,0.06,17.18,19.40,1.24,0.25,0.23,69.09,0,1.20,239.69,0.18,3.83,1.08,3.05,-2.41,-0.48,1.22,0.0,1.22,7,360,0.00,6.64,102,73,284.60,284.60,184.87,97.39,1.54,0,22431.39,66.37,7.22,0
877,145,18,28.78,251.22,107,145800.0,57.44,10.58,1392.0,0.18,104.7,0.21,0.23,0.28,0.18,0.10,31.70,20.54,0.38,0.20,0.23,55.85,0,1.03,221.97,0.87,5.07,0.04,2.00,-0.94,-0.24,1.10,0.0,1.10,11,720,0.00,13.29,82,50,402.49,284.60,215.11,92.20,1.87,0,2952.72,65.67,6.31,0

Shape of DataFrame:  (937, 50)

Categorical columns: []

Numerical columns: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49]

There are total 0 categorical and 50 numerical columns

Uniquess information of Dataset:

    column  unique_count  unique_percent
0        0           238       25.400213
1        1           297       31.696905
2        2           927       98.932764
3        3           933       99.573106
4        4           179       19.103522
5        5           375       40.021345
6        6           820       87.513340
7        7           618       65.955176
8        8           561       59.871932
9        9            57        6.083244
10      10           577       61.579509
11      11            59        6.296692
12      12            73        7.790822
13      13           107       11.419424
14      14            53        5.656350
15      15            91        9.711846
16      16           893       95.304162
17      17           810       86.446105
18      18           170       18.143010
19      19            53        5.656350
20      20            68        7.257204
21      21             9        0.960512
22      22             1        0.106724
23      23            92        9.818570
24      24             9        0.960512
25      25             8        0.853789
26      26             9        0.960512
27      27           308       32.870864
28      28           447       47.705443
29      29           392       41.835646
30      30           107       11.419424
31      31            42        4.482391
32      32             4        0.426894
33      33            45        4.802561
34      34           141       15.048026
35      35           110       11.739594
36      36             3        0.320171
37      37           758       80.896478
38      38             9        0.960512
39      39             9        0.960512
40      40           388       41.408751
41      41           220       23.479189
42      42           644       68.729989
43      43           649       69.263607
44      44           499       53.255069
45      45             2        0.213447
46      46           937      100.000000
47      47           169       18.036286
48      48           286       30.522946
49      49             2        0.213447

You can access this dataframe by typing '<report_obj>.unique_df'
To drop column with particular or minimum threshold use 'mlutils.drop_column_based_on_uniqueness_threshold(df, threshold=0)'

Description of Data:

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48,49
count,937.000000,937.000000,937.000000,937.000000,937.000000,9.370000e+02,937.000000,937.000000,937.000000,937.000000,937.000000,937.000000,937.000000,937.000000,937.000000,937.000000,937.000000,937.000000,937.000000,937.000000,937.000000,937.000000,937.0,937.000000,937.000000,937.000000,937.000000,937.000000,937.000000,937.000000,937.000000,937.000000,937.000000,937.000000,937.000000,937.000000,937.000000,937.000000,937.000000,937.000000,937.000000,937.000000,937.000000,937.000000,937.000000,937.000000,937.000000,937.000000,937.000000,937.000000
mean,81.588047,332.842049,698.707086,870.992209,84.121665,7.696964e+05,43.242721,9.127887,3940.712914,0.221003,109.892743,0.251441,0.311217,0.484664,0.182892,0.301932,77.412561,31.151921,0.909039,0.228815,0.289317,76.085624,0.0,0.642177,559.910694,0.578292,7.498196,0.608399,4.271110,-2.828420,-0.428869,1.824589,0.002785,1.821793,43.086446,2432.689434,0.006894,31.241857,91.189968,60.547492,933.928677,427.565582,255.435902,106.112519,5.014002,0.128068,7985.718004,61.694386,8.119723,0.043757
std,64.976730,1931.938570,599.965577,522.799325,45.361771,3.831151e+06,12.718404,3.588878,8167.427625,0.090316,61.460846,0.088132,0.121386,0.216859,0.082943,0.204695,304.329842,152.693334,0.675492,0.075410,0.105366,22.937473,0.0,0.299945,612.459280,0.702157,3.967966,0.845222,3.619406,1.621832,0.215617,0.638722,0.048988,0.643398,95.167329,5219.377585,0.005337,31.584838,21.984410,13.838898,1001.681331,715.391648,534.306194,135.617708,5.029151,0.334344,6854.504915,10.412807,2.908895,0.204662
min,1.000000,10.000000,1.920000,1.000000,0.000000,7.031200e+04,21.240000,0.830000,667.000000,0.020000,41.000000,0.020000,0.030000,0.050000,0.010000,0.010000,4.820000,1.960000,0.130000,0.020000,0.020000,47.660000,0.0,0.170000,132.780000,-0.710000,2.960000,-1.790000,1.440000,-7.810000,-1.370000,0.000000,0.000000,0.000000,3.000000,360.000000,0.000000,5.050000,64.000000,39.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,2051.500000,35.950000,5.810000,0.000000
25%,31.000000,20.000000,85.270000,444.200000,54.000000,1.250000e+05,33.650000,6.750000,1371.000000,0.160000,83.500000,0.200000,0.240000,0.330000,0.130000,0.130000,21.090000,11.680000,0.370000,0.180000,0.230000,55.850000,0.0,0.450000,221.970000,0.180000,4.660000,0.090000,2.640000,-3.250000,-0.530000,1.220000,0.000000,1.210000,12.000000,720.000000,0.000000,13.450000,78.000000,50.000000,450.000000,180.000000,90.800000,50.120000,2.370000,0.000000,3760.570000,65.720000,6.340000,0.000000
50%,64.000000,65.000000,704.370000,761.280000,73.000000,1.863000e+05,39.970000,8.200000,2090.000000,0.200000,99.800000,0.240000,0.290000,0.430000,0.170000,0.270000,34.720000,16.490000,0.700000,0.220000,0.270000,69.090000,0.0,0.500000,351.670000,0.870000,5.070000,0.480000,3.330000,-2.780000,-0.380000,1.950000,0.000000,1.950000,23.000000,1350.000000,0.010000,23.630000,82.000000,55.000000,685.420000,270.000000,161.650000,73.850000,3.850000,0.000000,5509.430000,65.930000,7.220000,0.000000
75%,124.000000,132.000000,1223.480000,1260.370000,117.000000,3.304680e+05,52.420000,10.760000,3435.000000,0.260000,115.400000,0.290000,0.350000,0.610000,0.220000,0.410000,65.950000,24.750000,1.060000,0.270000,0.320000,85.220000,0.0,0.960000,422.120000,1.010000,12.060000,0.980000,4.500000,-1.620000,-0.280000,2.170000,0.000000,2.170000,39.000000,2160.000000,0.010000,37.760000,99.000000,67.000000,1053.420000,460.980000,265.510000,125.810000,6.320000,0.000000,9521.930000,66.130000,7.840000,0.000000
max,352.000000,32389.000000,1893.080000,2724.570000,180.000000,7.131500e+07,82.640000,24.690000,160740.000000,0.740000,901.700000,0.660000,0.830000,1.230000,0.650000,1.120000,6058.230000,4061.150000,2.600000,0.650000,0.770000,126.080000,0.0,1.330000,2036.800000,1.830000,14.780000,5.720000,39.420000,1.280000,0.000000,2.980000,0.870000,2.980000,1695.000000,95310.000000,0.020000,441.230000,143.000000,86.000000,11949.330000,11500.000000,9593.480000,1748.130000,76.630000,1.000000,55128.460000,66.450000,15.440000,1.000000

Congrats!!, The Dataframe has NO NULL VALUES

In [4]:
mlp = Mlpurifier(df)

Dropped columns containing single value:  [22]

Checking for duplicate rows...
Dataframe contains no duplicate rows